services:
  - type: web
    name: deepfake-recognition
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: MODEL_URL
        value: https://drive.google.com/file/d/18KkpTqA7R9jifFE_YbE2CiPmJO81CTVL/view?usp=drive_link
        sync: false
